---
- hosts: "{{IM_HOST}}"
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ANSIBLE_IMAGE: grycap/ansible
    ANSIBLE_VERSION: devel2
    UDOCKER_VERSION: v1.1.3
  tasks:
    - name: Set Ansible version from env
      set_fact: ANSIBLE_VERSION={{ lookup('env','ANSIBLE_VERSION') }}
      when: lookup('env','ANSIBLE_VERSION') != ""

    # Some OSs does not have python by default
    - name: Check Python is installed
      raw: which python
      ignore_errors: yes
      register: python_exists
      changed_when: false

    - name: Bootstrap with python
      raw: sudo apt update; sudo apt install -y python; sudo yum install -y python; sudo zypper -n install python python-xml
      ignore_errors: yes
      register: python_install
      changed_when: python_install.stdout_lines|length > 1
      when: python_exists is failed

    - name: Get Facts
      setup:

    - name: EPEL
      yum: name=epel-release
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

    - name: Install curl
      package: name=curl state=present

    - name: Download udocker
      get_url:
        url: https://raw.githubusercontent.com/indigo-dc/udocker/{{ UDOCKER_VERSION }}/udocker.py
        dest: /usr/local/bin/udocker
        mode: "0755"

    - name: Install udocker
      command: udocker --allow-root install creates="{{ ansible_env.HOME }}/.udocker"

    - name: Pull ansible image
      command: udocker --allow-root pull {{ ANSIBLE_IMAGE }}:{{ ANSIBLE_VERSION }} creates="{{ ansible_env.HOME }}/.udocker/repos/{{ ANSIBLE_IMAGE }}/{{ ANSIBLE_VERSION }}"

    - name: Create container
      command: udocker --allow-root create --name=ansible {{ ANSIBLE_IMAGE }}:{{ ANSIBLE_VERSION }} creates="{{ ansible_env.HOME }}/.udocker/containers/ansible"
